name:                almanakk-cli
version:             2.0.7
github:              "rtrollebo/almanakk-cli"
license:             BSD3
author:              "Robert Trollebø"
maintainer:          "rtrollebo@gmail.com"
copyright:           "2023 Robert Trollebø"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rtrollebo/almanakk-cli#readme>

flags:
  use-external-lib:
    manual: true
    default: false


dependencies:
- base >= 4.7 && < 5
- time
- scientific
- containers >= 0.6.2.1
- optparse-applicative >= 0.17.1.0

when:
  - condition: flag(use-external-lib)
    dependencies:
      - almanakk-lib == 1.1.6
    cpp-options: -DUSE_EXTERNAL

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


library:
  source-dirs: src
  exposed-modules:
    - Almanakk.Application.Calendar
    - Almanakk.Application.Ephemeris
    - Almanakk.Application.External
    - Almanakk.Application.Phase
    - Almanakk.Application.Version
    - Almanakk.Application.View
    - Almanakk.Application.Calendar.Internal
    - Almanakk.Application.Phase.Internal
  other-modules:
    - Almanakk.Application.External.Mock   
  when:
    - condition: flag(use-external-lib)
      other-modules:
        - Almanakk.Application.External.Lib
      dependencies:
        - almanakk-lib == 1.1.6
      cpp-options: -DUSE_EXTERNAL

executables:
  almanakk-cli:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - almanakk-cli

tests:
  almanakk-cli-test:
    main:                AlmanakkCliTest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - almanakk-cli
    - HUnit == 1.6.2.0
